# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import srl_pb2 as srl__pb2


class SRLStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.resolve = channel.unary_unary(
        '/SRL/resolve',
        request_serializer=srl__pb2.Input.SerializeToString,
        response_deserializer=srl__pb2.Output.FromString,
        )


class SRLServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def resolve(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SRLServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'resolve': grpc.unary_unary_rpc_method_handler(
          servicer.resolve,
          request_deserializer=srl__pb2.Input.FromString,
          response_serializer=srl__pb2.Output.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'SRL', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
